cloud:
  aws:
    credentials:
      access-key: CLAVEEJEMPLO
      secret-key: SECRETOEJEMPLO
    region:
      static: REGIONEJEMPLO
    stack:
      auto: false

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://URLEJEMPLO:3306/casouso?autoReconnect=true&useSSL=false
    username: USEREJEMPLO
    password: PASSWORDEJEMPLO
  cloud:
    stream:
      bindings:
        generateFile-in-0:
          destination: channel01

application:
  bucket:
    name: BUCKETEJEMPLO
  file:
    name: NOMBREEJEMPLO

management:
  endpoints:
    web:
      exposure:
        include: health,info
