cloud:
  aws:
    credentials:
      access-key: CLAVEEJEMPLO
      secret-key: SECRETOEJEMPLO
    region:
      static: REGIONEJEMPLO
    stack:
      auto: false

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/demo
    username: root
    password: rootpw
  cloud:
    stream:
      bindings:
        generateFile-in-0:
          destination: channel02

application:
  bucket:
    name: BUCKETEJEMPLO
  file:
    name: NOMBREEJEMPLO

management:
  endpoints:
    web:
      exposure:
        include: health,info
